//! `deadsync-screens` — the reloadable hot unit for the menu.
//!
//! This crate compiles the **real** `screens/menu/render.rs` directly into a
//! `cdylib` via `#[path]`, so editing that file and rebuilding only this crate
//! produces a fresh renderer without recompiling the engine rlib. The engine
//! rlib is statically linked for every other type (`State`, `HostContext`,
//! `Actor`, components…). The cdylib exports exactly one symbol,
//! `deadsync_hot_entry`, returning a pointer to a `static HotHeader` whose
//! vtable the host validates and dispatches through (see `deadsync::hot`).
//!
//! Each hot surface is wired by [`hot_local_renders!`]: it maps a
//! `deadsync::hot::HotSurface` marker (which owns the *slot number* in the rlib)
//! to this crate's **local** render fn, generates a typed `LocalRender` impl, and
//! places a generic `thunk::<Surface>` at `Surface::SLOT` in the `static VTABLE`.
//! Because the slot comes from the rlib trait, the cdylib cannot desync slot
//! numbering from the host.
//!
//! NOTE (boundary safety): the render output crosses as **`actor_wire` bytes**,
//! not a `Vec<Actor>`. The included `render.rs` still mints some `&'static str`
//! font/texture keys that point into *this cdylib's* rodata, but they are
//! serialized as owned strings during encode and the host decodes them into
//! host-owned `Arc<str>`, so no cdylib-rodata pointer escapes inside a live
//! `Actor`. Such a key only exists within a single render call.
//!
//! SAFETY INVARIANT (thread-local scratch): [`SCRATCH`] is a cdylib-owned
//! `Vec<u8>` whose destructor and allocator live in *this* module. The runtime
//! must therefore **never unload a hot generation** (today it keeps every loaded
//! library mapped for the reloader's lifetime) — running this module's TLS
//! destructor after unload would be UB. The returned [`ActorBlob`] borrows this
//! buffer; the host decodes synchronously before the next hot call on the thread.

// The real render path, compiled into THIS crate so edits don't touch the rlib.
// Relative to `crates/deadsync-screens/src/`, the repo root is three levels up.
#[path = "../../../src/screens/menu/render.rs"]
mod render;

use deadsync::engine::present::actor_wire;
use deadsync::engine::present::actors::Actor;
use deadsync::hot::{
    ABI_VERSION, ActorBlob, BUILD_HASH, HotEntry, HotHeader, HotSurface, LAYOUT_HASH, MAGIC,
    MAX_SURFACES, MenuSurface, PANIC_STRATEGY, RENDER_OK, RENDER_PANIC, ScreenVTable,
};
use std::cell::RefCell;
use std::panic::{AssertUnwindSafe, catch_unwind};

thread_local! {
    /// Cdylib-owned encode scratch reused across frames. Cleared and refilled on
    /// every render; the returned `ActorBlob` borrows it until the next call.
    static SCRATCH: RefCell<Vec<u8>> = const { RefCell::new(Vec::new()) };
}

/// This cdylib's **local** real renderer for a surface. Distinct from
/// [`HotSurface::render`], which is the engine rlib's in-lib *fallback* (the
/// empty stub under `feature = "hot"`). One impl per surface, generated by
/// [`hot_local_renders!`].
trait LocalRender: HotSurface {
    fn local_render(state: &Self::State, ctx: &Self::Context, alpha: f32) -> Vec<Actor>;
}

/// Generic type-erased hot entry: reconstruct the surface's real `&State` /
/// `&Context` from the host's erased pointers, run the cdylib-local renderer
/// under `catch_unwind`, and encode the actors into the thread-local scratch.
/// One monomorphization per surface; `thunk::<S>` is placed at `S::SLOT` in the
/// vtable. Panics from the (hot-edited) render path are caught here and reported
/// as [`RENDER_PANIC`]; no panic crosses the `extern "C"` boundary.
extern "C" fn thunk<S: LocalRender>(state: *const (), ctx: *const (), alpha: f32) -> ActorBlob {
    let result = catch_unwind(AssertUnwindSafe(|| {
        // SAFETY: under the load-time LAYOUT_HASH / BUILD_HASH handshake these
        // pointers reference live `S::State` / `S::Context` of identical layout in
        // both artifacts; the host holds them valid for this call's duration and
        // we only ever *read* through them (never clone/drop a host `Arc`).
        let state = unsafe { &*(state as *const S::State) };
        let ctx = unsafe { &*(ctx as *const S::Context) };
        let actors = S::local_render(state, ctx, alpha);
        SCRATCH.with(|scratch| {
            let mut buf = scratch.borrow_mut();
            buf.clear();
            actor_wire::encode_actors(&actors, &mut buf);
            (buf.as_ptr(), buf.len())
        })
        // `actors` (and its cdylib-owned `Arc`s) drop here, freed by this
        // module's own allocator — nothing heap-owned escapes to the host.
    }));
    match result {
        Ok((ptr, len)) => ActorBlob {
            status: RENDER_OK,
            ptr,
            len,
        },
        Err(_) => ActorBlob {
            status: RENDER_PANIC,
            ptr: std::ptr::null(),
            len: 0,
        },
    }
}

/// Map each hot surface to its cdylib-local render fn, generating the
/// [`LocalRender`] impls and the `static VTABLE` (each `thunk::<S>` placed at
/// `S::SLOT`, all other slots `None`). The per-surface `let f: fn(&State, …)`
/// binding type-checks the render fn against the surface's associated types, so a
/// mismatched mapping fails to compile rather than casting the wrong layout at
/// runtime.
macro_rules! hot_local_renders {
    ( $( $surface:ty => $render:path ),+ $(,)? ) => {
        $(
            impl LocalRender for $surface {
                fn local_render(
                    state: &<$surface as HotSurface>::State,
                    ctx: &<$surface as HotSurface>::Context,
                    alpha: f32,
                ) -> Vec<Actor> {
                    let f: fn(
                        &<$surface as HotSurface>::State,
                        &<$surface as HotSurface>::Context,
                        f32,
                    ) -> Vec<Actor> = $render;
                    f(state, ctx, alpha)
                }
            }
        )+

        /// The dispatch table this cdylib publishes: a generic `thunk::<S>` at
        /// each surface's `S::SLOT`, every other slot left `None`.
        static VTABLE: ScreenVTable = {
            let mut entries: [Option<HotEntry>; MAX_SURFACES] = [None; MAX_SURFACES];
            $(
                entries[<$surface as HotSurface>::SLOT] = Some(thunk::<$surface> as HotEntry);
            )+
            ScreenVTable { entries }
        };
    };
}

hot_local_renders! {
    MenuSurface => render::get_actors,
}

/// `HotHeader` holds a raw `*const ()` vtable pointer, so it isn't `Sync`. The
/// header is immutable for the life of the dylib and only ever read, so wrapping
/// it to place it in a `static` is sound.
struct HeaderSync(HotHeader);
// SAFETY: `HEADER` is never mutated after construction; the pointer targets the
// `static VTABLE` in this same library, valid for the library's whole lifetime.
unsafe impl Sync for HeaderSync {}

static HEADER: HeaderSync = HeaderSync(HotHeader {
    magic: MAGIC,
    abi_version: ABI_VERSION,
    panic_strategy: PANIC_STRATEGY,
    _pad: [0; 3],
    size: size_of::<HotHeader>() as u32,
    layout_hash: LAYOUT_HASH,
    build_hash: BUILD_HASH,
    vtable: &VTABLE as *const ScreenVTable as *const (),
});

/// The single exported entry point. The host fetches this symbol, reads the
/// header, validates it against `deadsync::hot::EXPECTED`, and dispatches through
/// the vtable on success.
#[unsafe(no_mangle)]
pub extern "C" fn deadsync_hot_entry() -> *const HotHeader {
    &HEADER.0
}
